@startuml

note "Assuming all classes to implement \nthe abstract methods of their interfaces\n\n" as generalNotes

abstract class EntitySource {
    # DataSource dataSource
    # {static} <E extends EntityData, T extends UniqueEntity, R extends E> Try<R, SourceException> enrichEntityData(E, String, Map<UUID, T>, BiFunction<E, T, R>)
    # {static} <E extends EntityData, T1 extends UniqueEntity, T2 extends UniqueEntity, R extends E> Try<R, SourceException> enrichEntityData(E, String, Map<UUID, T1>, String, Map<UUID, T2>, TriFunction<E, T1, T2, R>)
    # {static} <T extends UniqueEntity> Try<T, SourceException> getLinkedEntity(EntityData, String, Map<UUID, T>)
    # {static} <E extends EntityData, T extends UniqueEntity, R extends E> Try<R, SourceException> optionallyEnrichEntityData(E, String, Map<UUID, T>, T, BiFunction<E, T, R>)
    # Stream<Try<NodeAssetInputEntityData, SourceException>> buildNodeAssetEntities(Class<T>, Map<UUID, OperatorInput>, Map<UUID, NodeInput>)
    # {static} Stream<Try<NodeAssetInputEntityData, SourceException>> nodeAssetInputEntityDataStream(Stream<Try<AssetInputEntityData, SourceException>>, Map<UUID, NodeInput>)
    # Stream<Try<AssetInputEntityData, SourceException>> buildAssetInputEntities(Class<? extends AssetInput>, Map<UUID, OperatorInput>)
    # {static} Stream<Try<AssetInputEntityData, SourceException>> assetInputEntityDataStream(Stream<Try<EntityData, SourceException>>, Map<UUID, OperatorInput>)
    # Stream<Try<EntityData, SourceException>> buildEntityData(Class<? extends UniqueEntity>)
    # {static} <S extends UniqueEntity> Map<UUID, S> unpackMap(Stream<Try<S, FactoryException>>, Class<S>) throws SourceException
    # {static} <S extends UniqueEntity> Set<S> unpackSet(Stream<Try<S, FactoryException>>, Class<S>) throws SourceException
    # {static} <S, E extends Exception> Stream<S> unpackSet(Stream<Try<S, E>>, Class<S>) throws SourceException
}

EntitySource <|-- GraphicSource
EntitySource <|-- RawGridSource
EntitySource <|-- ResultEntitySource
EntitySource <|-- SystemParticipantSource
EntitySource <|-- ThermalSource
EntitySource <|-- TypeSource

class GraphicSource {
    - TypeSource typeSource
    - RawGridSource rawGridSource
    - LineGraphicInputFactory lineGraphicInputFactory
    - NodeGraphicInputFactory nodeGraphicInputFactory
    + GraphicSource(TypeSource, RawGridSource, DataSource)
    + GraphicElements getGraphicElements() throws SourceException
    + GraphicElements getGraphicElements(Map<UUID, NodeInput>, Map<UUID, LineInput>) throws SourceException
    + Set<NodeGraphicInput> getNodeGraphicInput() throws SourceException
    + Set<NodeGraphicInput> getNodeGraphicInput(Map<UUID, NodeInput>) throws SourceException
    + Set<LineGraphicInput> getLineGraphicInput() throws SourceException
    + Set<LineGraphicInput> getLineGraphicInput(Map<UUID, LineInput>) throws SourceException
}

class RawGridSource {
    - TypeSource typeSource
    - NodeInputFactory nodeInputFactory
    - LineInputFactory lineInputFactory
    - Transformer2WInputFactory transformer2WInputFactory
    - Transformer3WInputFactory transformer3WInputFactory
    - SwitchInputFactory switchInputFactory
    - MeasurementUnitInputFactory measurementUnitInputFactory
    + RawGridSource(TypeSource typeSource, DataSource dataSource)
    + RawGridElements getGridData() throws SourceException
    + RawGridElements getGridData(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Map<UUID, LineInput>) throws SourceException
    + Map<UUID, NodeInput> getNodes() throws SourceException
    + Map<UUID, NodeInput> getNodes(Map<UUID, OperatorInput>) throws SourceException
    + Map<UUID, LineInput> getLines() throws SourceException
    + Map<UUID, LineInput> getLines(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<LineTypeInput>) throws SourceException
    + Set<Transformer2WInput> get2WTransformers() throws SourceException
    + Set<Transformer2WInput> get2WTransformers(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<Transformer2WTypeInput>) throws SourceException
    + Set<Transformer3WInput> get3WTransformers() throws SourceException
    + Set<Transformer3WInput> get3WTransformers(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<Transformer3WTypeInput>) throws SourceException
    + Set<SwitchInput> getSwitches() throws SourceException
    + Set<SwitchInput> getSwitches(Map<UUID, OperatorInput>, Map<UUID, NodeInput>) throws SourceException
    + Set<MeasurementUnitInput> getMeasurementUnits() throws SourceException
    + Set<MeasurementUnitInput> getMeasurementUnits(Map<UUID, OperatorInput>, Map<UUID, NodeInput>) throws SourceException
}

class ResultEntitySource {
    - SystemParticipantResultFactory systemParticipantResultFactory
    - ThermalResultFactory thermalResultFactory
    - SwitchResultFactory switchResultFactory
    - NodeResultFactory nodeResultFactory
    - ConnectorResultFactory connectorResultFactory
    - FlexOptionsResultFactory flexOptionsResultFactory
    + ResultEntitySource(DataSource)
    + ResultEntitySource(DataSource, String)
    + Set<NodeResult> getNodeResults() throws SourceException
    + Set<SwitchResult> getSwitchResults() throws SourceException
    + Set<LineResult> getLineResults() throws SourceException
    + Set<Transformer2WResult> getTransformer2WResultResults() throws SourceException
    + Set<Transformer3WResult> getTransformer3WResultResults() throws SourceException
    + Set<FlexOptionsResult> getFlexOptionsResults() throws SourceException
    + Set<LoadResult> getLoadResults() throws SourceException
    + Set<PvResult> getPvResults() throws SourceException
    + Set<FixedFeedInResult> getFixedFeedInResults() throws SourceException
    + Set<BmResult> getBmResults() throws SourceException
    + Set<ChpResult> getChpResults() throws SourceException
    + Set<WecResult> getWecResults() throws SourceException
    + Set<StorageResult> getStorageResults() throws SourceException
    + Set<EvcsResult> getEvcsResults() throws SourceException
    + Set<EvResult> getEvResults() throws SourceException
    + Set<HpResult> getHpResults() throws SourceException
    + Set<CylindricalStorageResult> getCylindricalStorageResult() throws SourceException
    + Set<ThermalHouseResult> getThermalHouseResults() throws SourceException
    + Set<EmResult> getEmResults() throws SourceException
}

class SystemParticipantSource{
    - TypeSource typeSource
    - RawGridSource rawGridSource
    - ThermalSource thermalSource
    - BmInputFactory bmInputFactory
    - ChpInputFactory chpInputFactory
    - EvInputFactory evInputFactory
    - FixedFeedInInputFactory fixedFeedInInputFactory
    - HpInputFactory hpInputFactory
    - LoadInputFactory loadInputFactory
    - PvInputFactory pvInputFactory
    - StorageInputFactory storageInputFactory
    - WecInputFactory wecInputFactory
    - EvcsInputFactory evcsInputFactory
    + SystemParticipantSource(TypeSource, ThermalSource, RawGridSource, DataSource)
    + SystemParticipants getSystemParticipants() throws SourceException
    + SystemParticipants getSystemParticipants(Map<UUID, OperatorInput>, Map<UUID, NodeInput>) throws SourceException
    + Set<BmInput> getBmPlants() throws SourceException
    + Set<BmInput> getBmPlants(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<BmTypeInput>) throws SourceException
    + Set<ChpInput> getChpPlants() throws SourceException
    + Set<ChpInput> getChpPlants(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<ChpTypeInput>, Map<UUID, ThermalBusInput>, Set<ThermalStorageInput>) throws SourceException
    + Set<EvInput> getEvs() throws SourceException
    + Set<EvInput> getEvs(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<EvTypeInput>) throws SourceException
    + Set<EvcsInput> getEvcs() throws SourceException
    + Set<EvcsInput> getEvcs(Map<UUID, OperatorInput>, Map<UUID, NodeInput>) throws SourceException
    + Set<FixedFeedInInput> getFixedFeedIns() throws SourceException
    + Set<FixedFeedInInput> getFixedFeedIns(Map<UUID, OperatorInput>, Map<UUID, NodeInput>) throws SourceException
    + Set<HpInput> getHeatPumps() throws SourceException
    + Set<HpInput> getHeatPumps(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<HpTypeInput>, Map<UUID, ThermalBusInput>) throws SourceException
    + Set<LoadInput> getLoads() throws SourceException
    + Set<LoadInput> getLoads(Map<UUID, OperatorInput>, Map<UUID, NodeInput>) throws SourceException
    + Set<PvInput> getPvPlants() throws SourceException
    + Set<PvInput> getPvPlants(Map<UUID, OperatorInput>, Map<UUID, NodeInput>) throws SourceException
    + Set<StorageInput> getStorages() throws SourceException
    + Set<StorageInput> getStorages(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<StorageTypeInput>) throws SourceException
    + Set<WecInput> getWecPlants() throws SourceException
    + Set<WecInput> getWecPlants(Map<UUID, OperatorInput>, Map<UUID, NodeInput>, Set<WecTypeInput>) throws SourceException
}

class ThermalSource {
    - TypeSource typeSource
    - ThermalBusInputFactory thermalBusInputFactory
    - CylindricalStorageInputFactory cylindricalStorageInputFactory
    - ThermalHouseInputFactory thermalHouseInputFactory
    + ThermalSource(TypeSource, DataSource)
    + Map<UUID, ThermalBusInput> getThermalBuses() throws SourceException
    + Map<UUID, ThermalBusInput> getThermalBuses(Map<UUID, OperatorInput>) throws SourceException
    + Set<ThermalStorageInput> getThermalStorages() throws SourceException
    + Set<ThermalStorageInput> getThermalStorages(Map<UUID, OperatorInput>, Map<UUID, ThermalBusInput>) throws SourceException
    + Set<ThermalHouseInput> getThermalHouses() throws SourceException
    + Set<ThermalHouseInput> getThermalHouses(Map<UUID, OperatorInput>, Map<UUID, ThermalBusInput>) throws SourceException
    + Set<CylindricalStorageInput> getCylindricStorages() throws SourceException
    + Set<CylindricalStorageInput> getCylindricStorages(Map<UUID, OperatorInput>, Map<UUID, ThermalBusInput>) throws SourceException
}

class TypeSource {
    - OperatorInputFactory operatorInputFactory
    - Transformer2WTypeInputFactory transformer2WTypeInputFactory
    - LineTypeInputFactory lineTypeInputFactory
    - Transformer3WTypeInputFactory transformer3WTypeInputFactory
    - SystemParticipantTypeInputFactory systemParticipantTypeInputFactory
    + TypeSource(DataSource)
    + Map<UUID, Transformer2WTypeInput> getTransformer2WTypes() throws SourceException
    + Map<UUID, Transformer3WTypeInput> getTransformer3WTypes() throws SourceException
    + Map<UUID, OperatorInput> getOperators() throws SourceException
    + Map<UUID, LineTypeInput> getLineTypes() throws SourceException
    + Map<UUID, BmTypeInput> getBmTypes() throws SourceException
    + Map<UUID, ChpTypeInput> getChpTypes() throws SourceException
    + Map<UUID, HpTypeInput> getHpTypes() throws SourceException
    + Map<UUID, StorageTypeInput> getStorageTypes() throws SourceException
    + Map<UUID, WecTypeInput> getWecTypes() throws SourceException
    + Map<UUID, EvTypeInput> getEvTypes() throws SourceException
}
@enduml