@startuml

' todo apapt
note "Assuming all classes to implement \nthe abstract methods of their interfaces\n\n" as generalNotes

abstract class EntitySource {
    - DataSource dataSource
    - <T extends AssetInput> Set<T> buildNodeAssetEntities(Class<T>, EntityFactory<T, NodeAssetInputEntityData>, Collection<NodeInput>, Collection<OperatorInput>, ConcurrentMap<Class<? extends UniqueEntity>, LongAdder>)
    - <T extends AssetInput> Set<T> buildNodeAssetEntities(Class<T>, EntityFactory<T, NodeAssetInputEntityData>, Collection<NodeInput>, Collection<OperatorInput>)
    - <T extends AssetInput> Set<T> buildAssetInputEntities(Class<T>, EntityFactory<T, AssetInputEntityData>, Collection<OperatorInput>)
    - <T extends AssetInput> Set<T> buildAssetInputEntities(Class<T>, EntityFactory<? extends InputEntity, EntityData>)
}
EntitySource <|-- GraphicSource
EntitySource <|-- RawGridSource
EntitySource <|-- ResultEntitySource
EntitySource <|-- SystemParticipantSource
EntitySource <|-- ThermalSource
EntitySource <|-- TypeSource

class GraphicSource {
    - TypeSource typeSource
    - RawGridSource rawGridSource
    - LineGraphicInputFactory lineGraphicInputFactory
    - NodeGraphicInputFactory nodeGraphicInputFactory
    - GraphicSource(TypeSource, RawGridSource, DataSource)
    - Optional<GraphicElements> getGraphicElements()
    - Set<NodeGraphicInput> getNodeGraphicInput()
    - Set<NodeGraphicInput> getNodeGraphicInput(Set<NodeInput>)
    - Set<LineGraphicInput> getLineGraphicInput()
    - Set<LineGraphicInput> getLineGraphicInput(Set<LineInput>)
}

class RawGridSource {
    - TypeSource typeSource
    - NodeInputFactory nodeInputFactory
    - LineInputFactory lineInputFactory
    - Transformer2WInputFactory transformer2WInputFactory
    - Transformer3WInputFactory transformer3WInputFactory
    - SwitchInputFactory switchInputFactory
    - MeasurementUnitInputFactory measurementUnitInputFactory
    - Optional<RawGridElements> getGridData()
    - Set<NodeInput> getNodes()
    - Set<NodeInput> getNodes(Set<OperatorInput>)
    - Set<LineInput> getLines()
    - Set<LineInput> getLines(Set<NodeInput>, Set<LineTypeInput>, Set<OperatorInput>)
    - Set<Transformer2WInput> get2WTransformers()
    - Set<Transformer2WInput> get2WTransformers(Set<NodeInput>, Set<Transformer2WTypeInput>, Set<OperatorInput>)
    - Set<Transformer3WInput> get3WTransformers()
    - Set<Transformer3WInput> get3WTransformers(Set<NodeInput>, Set<Transformer3WTypeInput>, Set<OperatorInput>)
    - Set<SwitchInput> getSwitches()
    - Set<SwitchInput> getSwitches(Set<NodeInput>, Set<OperatorInput>)
    - Set<MeasurementUnitInput> getMeasurementUnits()
    - Set<MeasurementUnitInput> getMeasurementUnits(Set<NodeInput>, Set<OperatorInput>)
}

class ResultEntitySource {
    - SystemParticipantResultFactory systemParticipantResultFactory
    - ThermalResultFactory thermalResultFactory
    - SwitchResultFactory switchResultFactory
    - NodeResultFactory nodeResultFactory
    - ConnectorResultFactory connectorResultFactory
    - FlexOptionsResultFactory flexOptionsResultFactory
    - ResultEntitySource(DataSource)
    - ResultEntitySource(DataSource, String)
    - Set<NodeResult> getNodeResults()
    - Set<SwitchResult> getSwitchResults()
    - Set<LineResult> getLineResults()
    - Set<Transformer2WResult> getTransformer2WResultResults()
    - Set<Transformer3WResult> getTransformer3WResultResults()
    - Set<FlexOptionsResult> getFlexOptionsResults()
    - Set<LoadResult> getLoadResults()
    - Set<PvResult> getPvResults()
    - Set<FixedFeedInResult> getFixedFeedInResults()
    - Set<BmResult> getBmResults()
    - Set<ChpResult> getChpResults()
    - Set<WecResult> getWecResults()
    - Set<StorageResult> getStorageResults()
    - Set<EvcsResult> getEvcsResults()
    - Set<EvResult> getEvResults()
    - Set<HpResult> getHpResults()
    - Set<CylindricalStorageResult> getCylindricalStorageResult()
    - Set<ThermalHouseResult> getThermalHouseResults()
    - Set<EmResult> getEmResults()
}

class SystemParticipantSource{
    - TypeSource typeSource
    - RawGridSource rawGridSource
    - ThermalSource thermalSource
    - BmInputFactory bmInputFactory
    - ChpInputFactory chpInputFactory
    - EvInputFactory evInputFactory
    - FixedFeedInInputFactory fixedFeedInInputFactory
    - HpInputFactory hpInputFactory
    - LoadInputFactory loadInputFactory
    - PvInputFactory pvInputFactory
    - StorageInputFactory storageInputFactory
    - WecInputFactory wecInputFactory
    - EvcsInputFactory evcsInputFactory
    - SystemParticipantSource(TypeSource, ThermalSource, RawGridSource, DataSource)
    - Optional<SystemParticipants> getSystemParticipants()
    - Set<BmInput> getBmPlants()
    - Set<BmInput> getBmPlants(Set<NodeInput>, Set<OperatorInput>, Set<BmTypeInput>)
    - Set<ChpInput> getChpPlants()
    - Set<ChpInput> getChpPlants(Set<NodeInput>, Set<OperatorInput>, Set<ChpTypeInput>, Set<ThermalBusInput>, Set<ThermalStorageInput>)
    - Set<EvInput> getEvs()
    - Set<EvInput> getEvs(Set<NodeInput>, Set<OperatorInput>, Set<EvTypeInput>)
    - Set<EvcsInput> getEvcs()
    - Set<EvcsInput> getEvcs(Set<NodeInput>, Set<OperatorInput>)
    - Set<FixedFeedInInput> getFixedFeedIns()
    - Set<FixedFeedInInput> getFixedFeedIns(Set<NodeInput>, Set<OperatorInput>)
    - Set<HpInput> getHeatPumps()
    - Set<HpInput> getHeatPumps(Set<NodeInput>, Set<OperatorInput>, Set<HpTypeInput>, Set<ThermalBusInput>)
    - Set<LoadInput> getLoads()
    - Set<LoadInput> getLoads(Set<NodeInput>, Set<OperatorInput>)
    - Set<PvInput> getPvPlants()
    - Set<PvInput> getPvPlants(Set<NodeInput>, Set<OperatorInput>)
    - Set<StorageInput> getStorages()
    - Set<StorageInput> getStorages(Set<NodeInput>, Set<OperatorInput>, Set<StorageTypeInput>)
    - Set<WecInput> getWecPlants()
    - Set<WecInput> getWecPlants(Set<NodeInput>, Set<OperatorInput>, Set<WecTypeInput>)
}

class ThermalSource {
    - TypeSource typeSource
    - ThermalBusInputFactory thermalBusInputFactory
    - CylindricalStorageInputFactory cylindricalStorageInputFactory
    - ThermalHouseInputFactory thermalHouseInputFactory
    - ThermalSource(TypeSource, DataSource)
    - Set<ThermalBusInput> getThermalBuses()
    - Set<ThermalBusInput> getThermalBuses(Set<OperatorInput>)
    - Set<ThermalStorageInput> getThermalStorages()
    - Set<ThermalStorageInput> getThermalStorages(Set<OperatorInput>, Set<ThermalBusInput>)
    - Set<ThermalHouseInput> getThermalHouses()
    - Set<ThermalHouseInput> getThermalHouses(Set<OperatorInput>, Set<ThermalBusInput>)
    - Set<CylindricalStorageInput> getCylindricStorages()
    - Set<CylindricalStorageInput> getCylindricStorages(Set<OperatorInput>, Set<ThermalBusInput>)
}

class TypeSource {
    - OperatorInputFactory operatorInputFactory
    - Transformer2WTypeInputFactory transformer2WTypeInputFactory
    - LineTypeInputFactory lineTypeInputFactory
    - Transformer3WTypeInputFactory transformer3WTypeInputFactory
    - SystemParticipantTypeInputFactory systemParticipantTypeInputFactory
    - TypeSource(DataSource)
    - Set<Transformer2WTypeInput> getTransformer2WTypes()
    - Set<Transformer3WTypeInput> getTransformer3WTypes()
    - Set<OperatorInput> getOperators()
    - Set<LineTypeInput> getLineTypes()
    - Set<BmTypeInput> getBmTypes()
    - Set<ChpTypeInput> getChpTypes()
    - Set<HpTypeInput> getHpTypes()
    - Set<StorageTypeInput> getStorageTypes()
    - Set<WecTypeInput> getWecTypes()
    - Set<EvTypeInput> getEvTypes()
}
@enduml