@startuml
database psql [
    <b> PostgreSQL
    ==
    grid
    --
    assets
    --
    types
    --
    graphics
    --
    weather
    __
    time series
]
database neo4j [
    <b> Neo4J
    ==
    grid
    --
    assets
]
folder projName.tar.gz {
folder assets {
file ev.csv
file pv.csv
file wec.csv
file asset_xyz.csv
}
folder grid
folder types
folder graphics
}
folder resources {
file projName_model.conf
file projName_simulation.conf
file load_parameter
file load_profiles
file wholesale_prices
}
cloud streams [
streams
==
weather
]
interface grid_source
interface assets_source
interface types_source
interface thermal_source
interface graphics_source
interface weather_source
interface time_series_source
interface config_source
agent inputAccumulator
node "Simulation"

grid_source --> psql
grid_source --> neo4j
grid_source --> grid

assets_source --> psql
assets_source --> assets

types_source --> psql
types_source --> types

thermal_source --> psql
thermal_source --> types

graphics_source --> psql
graphics_source --> graphics

weather_source --> psql
weather_source --> streams

time_series_source --> psql
time_series_source --> streams

config_source --> inputAccumulator

inputAccumulator --> grid_source
inputAccumulator --> assets_source
inputAccumulator --> types_source
inputAccumulator --> graphics_source
inputAccumulator --> weather_source
inputAccumulator --> time_series_source
inputAccumulator --> thermal_source

projName_model.conf --> config_source

config_source --> Simulation

inputAccumulator --> Simulation

@enduml