@startuml

abstract Class UniqueEntity{
    + UUID:  uuid
}

abstract Class ResultEntity{
    + ZonedDateTime:  timestamp
    + UUID:  inputModel
}

abstract Class SystemParticipantResult{
    + p: ComparableQuantity<Power>
    + q: ComparableQuantity<Power>
}

abstract Class ConnectorResult{
    + iAMag: ComparableQuantity<ElectricCurrent>
    + iAAng: ComparableQuantity<Angle>
    + iBMag: ComparableQuantity<ElectricCurrent>
    + iBAng: ComparableQuantity<Angle>
}

abstract Class TransformerResult{
    + tapPos: int
}

Class NodeResult{
    + vMag: ComparableQuantity<ElectricCurrent>
    + vAng: ComparableQuantity<Angle>
}

Class LineResult{

}

Class TransformerResult2wResult{
}

Class Transformer3wResult{
    + iCMag: ComparableQuantity<ElectricCurrent>
    + iCAng: ComparableQuantity<Angle>
}

Class LoadResult

Class FixedFeedInResult


Class BmResult


Class PvResult


Class ChpResult


Class WecResult

Abstract Class ThermalUnitResult {
    - qDot: ComparableQuantity<Power> [MW]
}

Class ThermalHouseResult {
    - indoorTemperature: ComparableQuantity<Temperature> [°C]
}

Abstract Class ThermalStorageResult {
    - energy: ComparableQuantity<Energy> [MWh]
}

Class CylindricalStorageResult {
  - fillLevel: ComparableQuantity<Dimensionless> [%]
}

Class EvcsResult


Class EvResult{
    + soc: double
    + systemUuid: UUID
    + id: String
}

Class StorageResult{
    + soc: double
}

Class SwitchResult{
    + closed: boolean
}

UniqueEntity <|-- ResultEntity
ResultEntity <|-- ConnectorResult
ResultEntity <|-- SystemParticipantResult
ResultEntity <|-- NodeResult
ResultEntity <|-- EvResult
ResultEntity <|-- ThermalUnitResult
SystemParticipantResult <|-- FixedFeedInResult
SystemParticipantResult <|-- BmResult
SystemParticipantResult <|-- PvResult
SystemParticipantResult <|-- ChpResult
SystemParticipantResult <|-- WecResult
SystemParticipantResult <|-- EvcsResult
SystemParticipantResult <|-- StorageResult
SystemParticipantResult <|-- LoadResult
ThermalUnitResult <|-- ThermalSinkResult
ThermalUnitResult <|-- ThermalStorageResult
ThermalSinkResult <|-- ThermalHouseResult
ThermalStorageResult <|-- CylindricalStorageResult
ConnectorResult <|-- SwitchResult
EvResult --> "uuid" EvcsResult

ConnectorResult <|-- LineResult
ConnectorResult <|-- TransformerResult
TransformerResult <|-- TransformerResult2wResult
TransformerResult <|-- TransformerResult3wResult

@enduml