@startuml
Interface GridTestData
Interface ComplexTopology
Interface SystemParticipantTestData
Interface TypeTestData

GridTestData <|-- ComplexTopology
GridTestData <|-- SystemParticipantTestData
GridTestData <|-- TypeTestData
@enduml