@startuml

package <gridname>(.tar.gz) {
    package input {
        package global {
            label "//bm_type.csv//\n//chp_type.csv//\n//ev_type.csv//\n//hp_type.csv//\nline_type.csv\n//operator_input.csv//\n//storage_type.csv//\ntransformer_2w_type.csv\n//transformer_3w_type.csv//\n//wec_type.csv//\n//wec_characteristic_input.csv//"
        }
        package grid {
            label "line_input.csv\n//measurement_unit_input.csv//\nnode_input.csv\n//switch_input.csv//\ntransformer_2_w_input.csv\n//transformer_3_w_input.csv//"
        }
        package "//thermal//" as th {
            label "//cylindrical_storage_input.csv//\n//thermal_bus_input.csv//\n//thermal_house_input.csv//"
        }
        package participants {
            label "//bm_input.csv//\n//chp_input.csv//\n//ev_input.csv//\n//evcs_input.csv//\n//fixed_feed_in_input.csv//\n//hp_input.csv//\n//load_input.csv//\n//pv_input.csv//\n//storage_input.csv//\n//wec_input.csv//"
            package //time_series// {
                label "//its_<uuid0>.csv//\n...\n//its_<uuidn>.csv//\n//rts_<uuid0>.csv//\n...\n//rts_<uuidn>.csv//\n\n//participant_to_time_series.csv//"
            }
        }
        package //graphics// as gr {
            label "//line_graphic_input.csv//\n//node_graphic_input.csv//"
        }

        grid -[hidden]- global
        participants -[hidden]- th
        th -[hidden]- gr
    }
}

@enduml